### ISSUE TITLE
Not an issue per se

### ISSUE THREAD

**Issue by pitakill** [Ompluscator/dynamic-struct#1]
Nice piece of software you have here!

I've got a doubt about if is possible to have methods on the dynamic structs built with this library. Or in other words, if the dynamic structs can implement a interface

Some light about it will be awesome

**Comment by Ompluscator** [comment]
Thx! 
I'm not completely sure about about interface implementation, but I had some thoughts to work on that, maybe even in next version :)

**Comment by Ompluscator** [comment]
I've tried many different approaches. Last one was by trying to attach anonymous field which implements some interface. Unfortunately, right now thats not possible: https://github.com/golang/go/issues/23063

For now, I would suggest usage of ToStruct method from reader - it would be possible to map complete dynamic struct to some struct, which than implements some interface.
