### ISSUE TITLE
Struct fields are in random order

### ISSUE THREAD

**Issue by saedx1** [Ompluscator/dynamic-struct#17]
Hi,
We were creating dynamic structs and using them with `parquet-go` to write parquet files, which works fine.
However, the order of the columns in our parquet files is different each time, we dug a little bit; and it turns out that in your struct builder you are storing fields in a map, which doesn't guarantee order when you create the final definition.
Would it be ok to support that? I can write up a Pull Request for that quickly as I've done it already.
Thanks

**Comment by Ompluscator** [comment]
Hi @saedx1 
Yes, that would be absolutely fine - thx!

**Comment by saedx1** [comment]
@Ompluscator One thing that would need to be done is tagging the merge commit with a new version tag (I believe v1.2.1), I've never done it after a PR so I'm not sure if that's exactly what's needed. Just to make sure other people with v.1.2.0 can update.
Thanks a lot :D that was my first Open source contribution!
