### ISSUE TITLE
Error: unreadable: could not resolve interface type

### ISSUE THREAD

**Issue by ivanNieto13** [Ompluscator/dynamic-struct#27]
Hi, I'm getting this error with example's code on README.

> instance := dynamicstruct.NewStruct().
				AddField("Integer", 0, `json:"int"`).
				AddField("Text", "", `json:"someText"`).
				AddField("Float", 0.0, `json:"double"`).
				AddField("Boolean", false, "").
				AddField("Slice", []int{}, "").
				AddField("Anonymous", "", `json:"-"`).
				Build().
				New()
				
<img width="643" alt="Screenshot 2023-01-25 at 13 22 44" src="https://user-images.githubusercontent.com/25516069/214665940-7b46cb87-ce45-4c1c-bcf4-2dc199f48bba.png">

**Comment by kshishkin82** [comment]
It is problem of gold and IDE. I have it is problem too but it is not affect to work app

**Comment by Ompluscator** [comment]
As it is related to IDE presentation of instance, it's not considered as issue.
