### ISSUE TITLE
How to set the value to the Structure after creating the new dynamic struct

### ISSUE THREAD

**Issue by mrkhanakia** [Ompluscator/dynamic-struct#6]
Live Example
https://play.golang.org/p/xEhdtxy-zSU

```
package main

import (
	"fmt"
	"reflect"
	dynamicstruct "github.com/ompluscator/dynamic-struct"
)



type User struct {
	UserEmail string
	UserPass  string
	Test      string
}

type DataTwo struct {
	UserAge string
}


func main() {
	instance := dynamicstruct.MergeStructs(User{}, DataTwo{}).
		Build().
		New()
	fmt.Println(reflect.TypeOf(instance))
	val := reflect.ValueOf(instance).Elem()
	fmt.Println(val.FieldByName("UserEmail").Interface().(string))

}
```

I want to set the values to the struct something like that so how to achieve that ?
```
a := instance {
  UserEmail: "test@test.com"
}
```

**Comment by Ompluscator** [comment]
Hi.

In general, I wanted to avoid direct direct setting of values inside dynamic structs. Main idea was/is to use tags (json, form...) to set values and than to read them via Reader, or to manipulate with validation rules, by changing them in runtime. I would suggest to use json.Unmarshall for setting values, where you can specify just one of them, if you need it.

To add functionality to set value for particular field is not a big deal, but is it really needed?

**Comment by mrkhanakia** [comment]
Basically i am creating an AUTH package in golang and i want the developers to add custom field to the exiting USER struct defined in my package without modifying the core package.

I want to achieve something like that https://play.golang.org/p/Wb_OtUdTKrc

So it would be great to have this functionality or you can point me in the right direction ?

**Comment by Ompluscator** [comment]
Go doesn't support pure polymorphic on by extending structs, like classes in any other OOP. In case of Go, it's more like decorating structs with other structs, than actual inheritance. So, your User struct will never know about any other struct which "inherited" User.

So, to set value - it depends what you want to use as your data source (API, database...). So depending on source, you can choose if you want to use dynamic struct to decode json, yaml, or database result, with some orm - which dynamic struct supports. I think it should not be expected to set value for user, without using some kind of data source.

And, in the end, if you really need to set value, this is workable solution in your case: https://play.golang.org/p/zCUid0axB4H
